<header>
    <a href="index.html"><img src="images/logo.png" alt="Delta Logo" id="logo"></a>
    <nav>
        <ul>
            <li class="nav_bar"><a class="nav_link" id="<?php if($page=='home'){echo 'on_page';}?>" href="index.php"> Home </a></li>
            <li class="nav_bar"><a class="nav_link" id="<?php if($page=='product'){echo 'on_page';}?>" href="product.php"> Browse </a></li>
            <li class="nav_bar"><a class="nav_link" id="<?php if($page=='enquire'){echo 'on_page';}?>" href="enquire.php"> Enquire </a></li>
            <li class="nav_bar"><a class="nav_link" id="<?php if($page=='manager'){echo 'on_page';}?>" href="manager.php"> Manager </a></li>
            <li class="nav_bar"><a class="nav_link" id="<?php if($page=='enhancements'){echo 'on_page';}?>" href="enhancements.php"> Enhancements </a></li>
            <li class="nav_bar"><a class="nav_link" id="<?php if($page=='about'){echo 'on_page';}?>" href="about.php"> About Us </a></li>
        </ul>
    </nav>
</header>
